feat/ 4673번 문제 추가
LK-Coding-Study/Java_Algorithm pull request #1
Opened 2023-01-25 13:22 UTC by ehdgjslee

## PR 설명
|번호|알고리즘|레벨|성공여부|
|---|---|---|---|
| 4673 | 브루트포스 | 실버5 | 실패 |

## 상세 설명
- 실패한 경우나 특이사항을 기록하려는 경우 추가

## 문제 링크
- [문제 링크 추가](https://www.acmicpc.net/problem/4673)

2023-01-31 14:34 UTC, idean3885 requested changes
문제 풀이 추가 후 재요청바람.

2023-02-01 14:14 UTC, idean3885 commented on src/com/lk/study/baekjoon/_4673/lee/Main.java
> +        List<Number> a = new ArrayList<>();
다른 풀이와 비교했을 때, 실행시간이 2배(반복문 두번) 정도 더 소요됩니다.
차주 스터디 때, 가능하다면 반복문을 줄여 소요시간을 줄일 수 있도록 알고리즘을 생각해보면 도움이 될 것 같습니다.

2023-02-01 16:22 UTC, ehdgjslee reviewed
## PR 설명
|번호|알고리즘|레벨|성공여부|
|---|---|---|---|
| 1065 | 브루트포스 | 실버4 | 실패 |

## 상세 설명
- 실패이유 : 시간 초과

## 문제 링크
- [문제 링크 추가](링크를 넣으세요)

2023-02-02 04:53 UTC, idean3885 requested changes
다른 문제 커밋 삭제 후 다시 요청바랍니다.

2023-02-02 04:53 UTC, idean3885 commented on src/com/lk/study/baekjoon/_1065/lee/Main.java
> +public class Main {
1065번은 브랜치 따로 생성해서 커밋 후 풀리퀘스트 요청하시기 바랍니다.

2023-02-07 10:08 UTC, idean3885 approved these changes

2023-02-14 11:01 UTC, merged